### PR TITLE
pressbooks/pressbooks#346 Add anchors for footnote references.

### LINKED ISSUE #346: Correctly link footnotes on Word import
When importing a single-chapter Word document with end-notes, the end notes and their references are converted. However, linking between them is incomplete.

The references have links of the form `<a href="#sdfootnote1sym">` and the footnotes themselves have links, around their numbers, of the form `<a href="#sdfootnote1anc">`, but each is missing the necessary anchors to make the links from the other work.

That said, it looks like #103 is mostly working, aside from this; importing a multi-chapter Word file did cause the end-notes to be distributed appropriately among the different chapters.

### PR DESCRIPTION
**Pull request by crism**
This should fix #346.

### CODE REVIEW

**Comment by connerbw** [comment]
Can you resubmit and preserve the formatting in `ooxml/xsl/docx2html.xsl`?

The diff is not very useful, difficult to review.

**Comment by crism** [comment]
Sorry, @connerbw—I couldn’t see any consistency to what was there (tabs plus varying numbers of spaces), so I let my editor do what it wanted.

A `diff -b`:
```diff
--- a/includes/modules/import/ooxml/xsl/docx2html.xsl
+++ b/includes/modules/import/ooxml/xsl/docx2html.xsl
@@ -3270,7 +3270,6 @@
   </xsl:template>
 
   <xsl:template name="DisplayRContent">
-
     <xsl:choose>
        <xsl:when test="ancestor::w:sdtContent/preceding-sibling::w:sdtPr[1]/w:citation">
         <xsl:element name="cite">
@@ -3278,7 +3277,8 @@
         </xsl:element>
       </xsl:when>
       <xsl:when test="w:rPr/w:rStyle/@w:val = 'FootnoteReference'">
-                                     <xsl:element name="a">
+         <xsl:variable name="fnanchor" select="concat('#sdfootnote', w:footnoteReference/@w:id,'anc')"/>
+        <xsl:element name="a" name="{$fnanchor}" id="{$fnanchor}">
           <xsl:attribute name="href">
              <xsl:value-of select="concat('#sdfootnote', w:footnoteReference/@w:id,'sym')"/>
           </xsl:attribute>
@@ -3288,7 +3288,8 @@
         </xsl:element>
       </xsl:when>
       <xsl:when test="w:endnoteReference">
-                                     <xsl:element name="a">
+         <xsl:variable name="fnanchor" select="concat('#sdfootnote', w:endnoteReference/@w:id,'anc')"/>
+        <xsl:element name="a" name="{$fnanchor}" id="{$fnanchor}">
           <xsl:attribute name="href">
              <xsl:value-of select="concat('#sdfootnote', w:endnoteReference/@w:id,'sym')"/>
           </xsl:attribute>
@@ -3297,9 +3298,7 @@
           </xsl:element>
         </xsl:element>                       
       </xsl:when>
-                     
       <xsl:otherwise>
-                             
         <xsl:apply-templates select="*"/>
       </xsl:otherwise>
     </xsl:choose>
@@ -3653,17 +3652,7 @@
     </xsl:variable>
     <xsl:choose>
       <xsl:when test="$rStyleId='' and $styleMod=''">
-        <xsl:choose>
-          <xsl:when test="not($themeStyle='')">
-
-              <xsl:call-template name="DisplayRContent"/>
-
-          </xsl:when>
-          <xsl:otherwise>
         <xsl:call-template name="DisplayRContent"/>
-          </xsl:otherwise>
-        </xsl:choose>
-
         <xsl:if test="$pr.listSuff = $prListSuff_space">
           <xsl:text> </xsl:text>
         </xsl:if>
```
To summarize, the two `<a>` start-tags for footnote and endnote references have `name` and `id` attributes added. Also, an if-x-then-a-else-a antipattern was cleaned up.

**Comment by crism** [comment]
Agh, sorry—except, of course, there’s a stupid mistake. I’ll fix it, and restore the formatting, and check that in.

**Comment by crism** [comment]
And… that should do it, I think.

**Comment by greatislander** [comment]
@crism Can you provide a representative Word document that I can use to test this PR? Thanks.

**Comment by crism** [comment]
A small test document is attached.
[End Note Test Document.docx](https://github.com/pressbooks/pressbooks/files/146977/End.Note.Test.Document.docx)

**Comment by greatislander** [comment]
Thanks for your contribution, @crism. Works as expected.

**Comment by crism** [comment]
Awesome, @connerbw and @greatislander. Looking forward to putting this in play.

**Pull request merged**
