### PR TITLE
Changed queries in PB-Network-Managers files to use $wpdb-> instead of 'wp' table prefix

### PR DESCRIPTION
**Pull request by rootl**
Greetings,

We were receiving this error in our log files: 

<i>WordPress database error Table 'xxxourdbnamexxx.wp_sitemeta' doesn't exist for query SELECT * FROM wp_sitemeta WHERE meta_key = "pressbooks_network_managers" made by require_once('wp-admin/admin.php'), do_action('admin_init'), call_user_func_array, PressBooks\Admin\NetworkManagers\restrict_access</i>

Our database prefix is not 'wp_'  .    I rewrote queries to call $wpdb->sitemeta  instead of   wp_sitemeta.     No more errors, and our site functions properly.

I rewrote all the queries in the following files:
wp-content/plugins/pressbooks/includes/admin/pb-network-managers.php
wp-content/plugins/pressbooks/includes/admin/class-pb-network-managers-list-table.php

For example:

wp-content/plugins/pressbooks/includes/admin/pb-network-managers.php  

Line 42: 

    $restricted = $wpdb->get_results( 'SELECT * FROM wp_sitemeta WHERE meta_key = "pressbooks_network_managers"' );  

becomes: 

    $restricted = $wpdb->get_results( "SELECT * FROM $wpdb->sitemeta WHERE meta_key = 'pressbooks_network_managers'" );

I would like to submit these changes for inclusion in Pressbooks.  Thank you.

### CODE REVIEW

**Comment by greatislander** [comment]
Hi @rootl—thanks for this, but can you resubmit a pull request that reflects just the modifications you would like to include? (E.g. update your fork from upstream/dev, then make your changes, then resubmit?) I'd like to be able to evaluate a PR with just your changes.

**Comment by rootl** [comment]
My total apologies.. I downloaded a new git client and ....b0rked it up.
I will  send this properly. Thanks.

On Fri, Nov 6, 2015 at 2:23 PM, Ned Zimmerman <notifications@github.com>
wrote:

> Hi @rootl <https://github.com/rootl>—thanks for this, but can you
> resubmit a pull request that reflects just the modifications you would like
> to include? (E.g. update your fork from upstream/dev, then make your
> changes, then resubmit?) I'd like to be able to evaluate a PR with just
> your changes.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pressbooks/pressbooks/pull/306#issuecomment-154508127>
> .
>



-- 
Leah M Root
Library Publishing/Web Services Developer
Milne Library, SUNY Geneseo <http://www.geneseo.edu/library/leah-root>
1 College Circle, Geneseo, NY 14454
585-245-6061 | cell 585-802-4676
rootl@geneseo.edu
@RootLeah <https://twitter.com/RootLeah>

**Comment by greatislander** [comment]
No problem! Much appreciated.

**Comment by connerbw** [comment]
I've manually integrated the patch.

https://github.com/pressbooks/pressbooks/commit/74068266538bd1e6edc9b45091cbba4a28a745ab

Thanks @rootl!

**Comment by rootl** [comment]
Thank you so much! I was going to re-submit. I appreciate this.



On Sat, Nov 7, 2015 at 9:40 AM, Dac Chartrand <notifications@github.com>
wrote:

> I've manually integrated the patch.
>
> 7406826
> <https://github.com/pressbooks/pressbooks/commit/74068266538bd1e6edc9b45091cbba4a28a745ab>
>
> Thanks @rootl <https://github.com/rootl>!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pressbooks/pressbooks/pull/306#issuecomment-154711312>
> .
>



-- 
Leah M Root
Library Publishing/Web Services Developer
Milne Library, SUNY Geneseo <http://www.geneseo.edu/library/leah-root>
1 College Circle, Geneseo, NY 14454
585-245-6061 | cell 585-802-4676
rootl@geneseo.edu
@RootLeah <https://twitter.com/RootLeah>

**Pull request closed without merging**
