### PR TITLE
Contributor fixes

### PR DESCRIPTION
**Pull request by arzola**
This PR Address #2330 

### How to test

1. Review on your local environment the contributor role is changed to collaborator without affecting anything else.
2. Review the Contributor back matter type is available for existent books

### CODE REVIEW

**Review by SteelWagstaff — CHANGES_REQUESTED** [review]
Requested changes:
1. Contributors back matter type now exists, but I notice that the role headings are h3 elements. These should be `<h2>` and don't need special styling.

2. Contributor has been changed to collaborator in most places, but not in 'Users' widget on book admin menu:
Screenshot from 2021-09-01 09-07-37

3. We should also change contributor to 'collaborator' in pressbooks-network-analytics in several places (can fix in separate PR). The user list, the user list drop downs, and the user info page:
Screenshot from 2021-09-01 09-09-07
Screenshot from 2021-09-01 09-11-24
Screenshot from 2021-09-01 09-10-50
Screenshot from 2021-09-01 09-10-16

**Comment by arzola** [comment]
@SteelWagstaff I sent the required changes and also I opened a PR in https://github.com/pressbooks/pressbooks-network-analytics/pull/138

**Review by SteelWagstaff — CHANGES_REQUESTED** [review]
Looking better, but users widget still shows 'Contributor' in one place: 
Screenshot from 2021-09-03 08-52-47

We need to fix that here: https://github.com/pressbooks/pressbooks/blob/6e78377256149cd9bcd6e48b0d76ebf3e0d60c46/inc/admin/dashboard/namespace.php#L333-L339

**Comment by arzola** [comment]
@SteelWagstaff ready for your review

**Review by SteelWagstaff — APPROVED** [review]
LGTM!

**Pull request merged**
