### PR TITLE
adding wp api rest routes, support for custom post types

### PR DESCRIPTION
**Pull request by bdolor**
This adds WP REST API support for custom post types. 

details here: https://packagist.org/packages/bccampus/rest-routes

### CODE REVIEW

**Comment by greatislander** [comment]
Hi @bdolor, this looks good but I have a few questions:

1. Should we instead add core REST API support on registration for our custom post types (I've already tested this but have held off on implementing—see point 3);
2. Assuming point 1, should we let users install this as a standalone plugin if they need to enable REST API support for other post types?
3. What are your thoughts are on the utility of exposing individual chapters, front/back matter and parts via the core REST API before we have an endpoint that exposes the book structure as a whole via the same REST API? Is that jumping the gun?

**Comment by bdolor** [comment]
1. No, I don't think we should. Instead we would want to consider the plugin registration event as an appropriate time to register the PB custom post types. It could be enabled by default, on the condition that the plugin detects that it's in a PB environment and is PB compatible.
2. Yes, I think we should. Activating a plugin instead of writing this into core follows the principle of modularity. Giving admin users the option to enable/disable makes this functionality usable across a wider variety of use cases.
3. We could frame any questions around timing with a release early, release often paradigm. Features could be shipped early in a minimal state, then improved further in future changes. I'd be open to putting that on the road map.

**Comment by greatislander** [comment]
Closing in favour of registering core post type routes internally.

**Comment by greatislander** [comment]
See also: #472.

**Pull request closed without merging**
