### PR TITLE
Allow png alpha channel on resize function

### PR DESCRIPTION
**Pull request by arzola**
This PR solves #2127 

Unit tests added

### How to test

1. Add a transparent background PNG in one of your chapters
2. Activate the option to resize and compress images on theme options
3. Export the book as an ePub and review the image still preserve the transparent background.

### CODE REVIEW

**Comment by richard015ar** [comment]
## Test notes
I tested adding a transparent .png image format on a front-matter section, I checked the `Show in exports` checkbox in the "Organize" secttion for the front matter, and finally I exported the book in .epub format. 
I used https://products.groupdocs.app/viewer to view the book exported properly.
I was able to confirm the solution works, the image is displayed as expected.

I also repeated the process with other images and other chapters and those cases also worked.

When I added a caption, alt text and link (custom URL) to the image, I am able to see the chapter in the web format:
Screenshot from 2021-04-14 09-50-10
 
But when I exported that to .epub, I see an error in the interface:
```
Warning: The export has validation errors. See logs for more details.
```
I, also see the epub file exported does not display the chapter as expected, only displaying an empty page.

**Comment by SteelWagstaff** [comment]
@richard015ar these testing notes are great. Can you share the epub validation logs? If you go to settings->export in the book dashboard there's a email validation logs setting you can turn on 
Screenshot from 2021-04-14 09-28-18

I think they're also stored locally, but I can't remember where off hand. It would be interesting to see if the same validation errors appear for a book created on a production/staging network to determine if this is related to the changes in this branch of another problem.

**Comment by richard015ar** [comment]
This is the error displayed in my logs:
```
[14-Apr-2021 18:52:19 UTC] \PressBooks\Export\Epub201\fetchAndSaveUniqueImage is_valid_image, not a valid image 
[14-Apr-2021 18:52:19 UTC] Pressbooks\Modules\Export\Epub\Epub201
Array
(
    [time] => Wed Apr 14 18:52:19 2021
    [user] => admin
    [site_url] => https://pressbooks.test/theonboarding
    [blog_id] => 2
    [theme] => McLuhan
)
```
It comes from: https://github.com/pressbooks/pressbooks/blob/dev/inc/modules/export/epub/class-epub201.php#L2138

Looks like we should debug this function: https://github.com/pressbooks/pressbooks/blob/567ee126158fe4211d0bea6cd17ec7b809859f74/inc/image/namespace.php#L109

**Comment by richard015ar** [comment]
Image used and video replicating the issue: 

https://user-images.githubusercontent.com/13248424/114767672-ee31ca00-9d35-11eb-96a7-bc0f9dbb83a0.mp4

dev

**Comment by richard015ar** [comment]
Actually it is happening on Integrations, so I could confirm the issue is not related to this change. 
@SteelWagstaff probably we could research this case in a separate ticket?

**Comment by SteelWagstaff** [comment]
@richard015ar I agree -- let's open a separate bug report for what you've found here, thanks.

**Review by SteelWagstaff — APPROVED** [review]
LGTM

**Pull request merged**
