### PR TITLE
Remove MOBI export and references

### PR DESCRIPTION
**Pull request by SteelWagstaff**
This PR removes the MOBI export option and most MOBI related references from Pressbooks. Partial fix for https://github.com/pressbooks/pressbooks/issues/2193 and fix for https://github.com/pressbooks/pressbooks/issues/1859. 

It also makes a small change to the export format menu, moving 
PressbooksXML and Thin Common Cartridge with weblinks to the 'supported formats' column and renaming the EPUB 2.01 export option.

Screenshot from 2021-07-15 19-38-14

**To test:**
1. Turn on ability to distribute files from home page
1. Open a book and create a MOBI export
1. Create an EPUB export and confirm that it does not have validation errors
1. Switch to this branch and open the export menu in any book
1. Check to see that MOBI export no longer appears in the menu
1. Check to see that the previously created MOBI file still appears in the list of previously exported files & can still be downloaded from the book's home page.
1. Confirm that EPUB 2.01 exports do appear in the menu 
1. Create an EPUB export and confirm that it still does not have validation errors

### CODE REVIEW

**Review by fdalcin — COMMENTED** [review]
@SteelWagstaff LGTM. My only question is, should we also remove styling related to MOBI ([see here](https://github.com/pressbooks/pressbooks/blob/dev/assets/src/styles/export.scss#L127-L133))?

Confirming that MOBI option isn't present anymore
image

MOBI previously generated is still available
Screen Shot 2021-07-19 at 14 36 34

Still possible to download MOBI files previously generated 
Screen Shot 2021-07-19 at 14 37 25

**Comment by SteelWagstaff** [comment]
@fdalcin those images are displayed on the export page after exports have been produced 
Screenshot from 2021-07-19 11-03-05. i think we should keep it so the display page works as expected

**Comment by fdalcin** [comment]
Makes sense, I thought they were related to the exporting process. My bad.

**Review by fdalcin — APPROVED** [review]

**Comment by SteelWagstaff** [comment]
@greatislander are you willing to take a quick look at this before we merge to make sure we're not missing anything?

**Pull request merged**
