### PR TITLE
chore: Add Boğaziçi University (Bosphorus University) to institutions list

### PR DESCRIPTION
**Pull request by cmurtagh**
As requested in the community forum

### CODE REVIEW

**Review by SteelWagstaff — CHANGES_REQUESTED** [review]
Thanks for submitting this, Christopher. The JSON structure is a bit wacky in this file. Although the titles are 'country' and 'region' -- for most countries outside the US and Canada these are actually used for Continent and Country. So in this case we'd want to set Europe as the Country and Turkey as the Region. Their institution code would use EU for the Country and the three letter ISO code for Turkey (TUR) in the region place. 

In hindsight, a better naming convention would probably have been 'region' and 'subregion', but these labels aren't displayed to users anywhere in the front-end, so refactoring it hasn't been a priority.

**Comment by SteelWagstaff** [comment]
I pushed a friendly commit that updates the values. The other question I have is whether we should use the university's official name 'Boğaziçi University' rather than Bosphorus University. I think probably yes?

**Comment by cmurtagh** [comment]
I'm all for having the official name, yes. 

Question: Most of Turkey isn't in Europe, but this institution is. If we get another request from an institution in Ankara, would we put that in Asia/Turkey?

**Comment by SteelWagstaff** [comment]
Good question. We have a few options here. We can indicate that Turkey is in Europe, indicate that Turkey is in Asia, or simply display Turkey (without a parent region).
Here's what the user would see with the PR as it stands now:
Screenshot from 2024-02-29 08-04-21
Here's what would be displayed if we put Turkey in Asia or without a geographic subregion:
Screenshot from 2024-02-29 08-04-56

What do you think is best here? This is a complex geographical question, and a pretty trivial choice for us :joy:

**Comment by cmurtagh** [comment]
Can we have both? Turkish institutions in Europe and also in Asia?

**Comment by cmurtagh** [comment]
My vote would be to keep the PR as it is now (Europe/Turkey) and when we add another institution that isn't from Western Istanbul, we'll figure it out.

**Comment by SteelWagstaff** [comment]
We've decided to use the official name and to go with Turkey as a country without regions for now. Will display like this:
Screenshot from 2024-02-29 08-14-56

**Review by SteelWagstaff — APPROVED** [review]

**Pull request merged**
