### PR TITLE
Undo css changes and apply fix facebook buttom

### PR DESCRIPTION
**Pull request by colomet**

### CODE REVIEW

**Comment by greatislander** [comment]
@colomet I just merged your previous pull request—this is a duplicate, no?

**Comment by colomet** [comment]
you ask me to undo and to place in a better place. That is what i did it. Is it correct now?

**Comment by greatislander** [comment]
When you make changes to the branch that you have opened a pull request from, the original pull request is updated. So there was no need to open an additional pull request.

**Comment by greatislander** [comment]
I merged your previous PR which included all your updates based on my feedback: https://github.com/pressbooks/pressbooks/commit/5271d6756e3d5bf06f9dbeb812852145312d039a

**Comment by colomet** [comment]
ok. sorry. it wont happen again. i don´ use to collaborate here on Git. It will be without problems the next time.

**Pull request closed without merging**
