### PR TITLE
feat: expose password protected posts for migration tool

### PR DESCRIPTION
**Pull request by richard015ar**
Issues: 
- https://github.com/pressbooks/pressbooks/issues/1863
- https://github.com/pressbooks/pressbooks/issues/2883

This PR: 
- Exposes password protected content when the `pb_set_api_items_permission` filter is true (migration)
- Removes the `CustomType` class and use the `Api\Endpoint\Post` instead to continue extending the custom post type through this one. All custom permissions applied through the `pb_set_api_items_permission` hook are moved to the Post class.
- Fixes the test issues described in https://github.com/pressbooks/pressbooks/issues/2883

### Testing
To test, we should follow the migration flow on textopress and dev.pressbooks.pub. We need to test a complete migration flow with different type of books and use cases to make sure the API and cloning routine is working as expected after the CustomType replacement.

### CODE REVIEW

**Review by greatislander — COMMENTED** [review]
This fixes the issues I was working on in #2849. You could add the test for the parts API I wrote for that PR to increase coverage further:

```php
    /**
	 * @group api
	 */
	public function test_partsEndpoint() {
		$server = $this->_setupBookApi();

		new Posts('part');

		$visible_part = [
			'post_type'    => 'part',
			'post_title'   => 'Visible',
			'post_content' => 'This space intentionally left blank.',
			'post_status'  => 'publish',
		];
		$invisible_part = [
			'post_type'    => 'part',
			'post_title'   => 'Invisible',
			'post_content' => 'This space intentionally left blank.',
			'post_status'  => 'publish',
		];

		$visible_id = $this->factory()->post->create_object( $visible_part );
		delete_post_meta( $visible_id, 'pb_part_invisible' );

		$invisible_id = $this->factory()->post->create_object( $invisible_part );
		update_post_meta( $invisible_id, 'pb_part_invisible', 'on' );

		$request = new \WP_REST_Request( 'GET', "/pressbooks/v2/parts/{$visible_id}" );
		$response = $server->dispatch( $request );
		$data = $response->get_data();

		$this->assertFalse($data['meta']['pb_part_invisible']);
		$this->assertEquals('', $data['meta']['pb_part_invisible_string']);

		$request = new \WP_REST_Request( 'GET', "/pressbooks/v2/parts/{$invisible_id}" );
		$response = $server->dispatch( $request );
		$data = $response->get_data();

		$this->assertNull($data['meta']['pb_part_invisible']);
		$this->assertEquals('on', $data['meta']['pb_part_invisible_string']);
	}
```

**Comment by fdalcin** [comment]
Thank you @greatislander. I’ll review the PR on Monday and we’ll include this extra test, thanks for the fixes.

**Comment by greatislander** [comment]
I've opened a PR against this branch with the changes— tests pass for me locally. You should be able to merge https://github.com/pressbooks/pressbooks/pull/2898 into this PR branch and then merge this and the issue will be resolved.

**Review by fdalcin — APPROVED** [review]
LGTM, thank you @richard015ar 

We need to test it thoroughly on integrations, dev.pressbooks.pub, and textopress because it was not possible to test using my local PHP 8 setup.

**Pull request merged**
