### PR TITLE
Add wp_filter to append content to chapter exports

### PR DESCRIPTION
**Pull request by monkecheese**
For content exported in html format, this allows another plugin
to register a wordpress filter that will append content to the
end of a chapter.

### CODE REVIEW

**Comment by monkecheese** [comment]
We have per-page citations/attributions that we would like to add to exports using this method.

**Comment by hughmcguire** [comment]
Hi @monkecheese FYI we're in the process of clarifying the pathway for new PB features -> pull requests... roughly what we envisage is: 
* step 1: stand-alone pressbooks-ready plugin 
* step 2: testing, feedback etc
* step 3: (if it makes sense) merge into Pressbooks

We'll have some more info soon, and I will be reaching out to David and Bracken shortly to get some input.

**Comment by greatislander** [comment]
@monkecheese Looking at this again. Can you show me how your filter is used in your other plugin (e.g. in a Gist or something)? I'm thinking it might make sense to have six hooks in total:

`pb_prepend_front_matter_content`
`pb_prepend_chapter_content`
`pb_prepend_back_matter_content`
`pb_append_front_matter_content`
`pb_append_chapter_content`
`pb_append_back_matter_content`

(Thoughts, @hughmcguire?)

**Comment by monkecheese** [comment]
Here's a link to our plugin that would use this hook: 

https://github.com/lumenlearning/candela-citation/blob/master/candela-citation.php

The `add_citations` function uses it to return per-page citation data to included with the export.

**Comment by greatislander** [comment]
Okay, I think this is a good approach. Canyou update your PR with the following:

- [ ] Add append content support to front and back matter as well using specific filters for those post types (it looks like your citations plugin supports those but this PR wouldn't in its current form)
- [ ] Rename the filters to `pb_append_front_matter_content`,  `pb_append_chapter_content` and `pb_append_back_matter_content`?

Then I will be happy to merge.

**Comment by monkecheese** [comment]
I made the changes you requested @greatislander in this latest commit: 

https://github.com/pressbooks/pressbooks/pull/399/commits/4ccf227190b83dc8b713a8461a317325d377a7d9

My tests indicate that everything works as it should.  Let me know if there's anything I missed.

**Comment by greatislander** [comment]
Thanks @monkecheese!

**Pull request merged**
