### PR TITLE
Added Accessibility Plug-in for web-view and PDF export

### PR DESCRIPTION
**Pull request by BakingSoda**
The plug-in gives user option to modify the font size, line spacing of the web-view of the book and PDF export for accessibility purposes. This feature came out of the accessibility testing with CAPER (Centre for Accessible Post-secondary Education Resources BC - See more at: http://tlc.ecuad.ca/centre-for-accessible-post-secondary-education-resources-bc-caper-bc/ ).

Web-view: 
Added button to enlarge font size and line spacing when toggled;
To enable this function, in the Admin interface: Appearance-> Theme options->Web 
option, check Increase Font Size for Accessibility:
screen shot 2015-03-05 at 1 21 15 pm

Before:
screen shot 2015-03-05 at 1 41 28 pm

After:
screen shot 2015-03-05 at 1 40 59 pm

PDF export:
Added option to enlarge font size and line spacing of PDF export;
To enable this function, in the Admin interface: Appearance-> Theme Options->PDF Options, check Increase Font Size for Accessibility:
screen shot 2015-03-05 at 1 21 53 pm

Before:
screen shot 2015-03-05 at 1 48 16 pm

After:
screen shot 2015-03-05 at 1 47 57 pm

### CODE REVIEW

**Comment by greatislander** [comment]
Thanks for this, @BakingSoda and @bdolor. Will review and get back to you ASAP.

**Comment by hughmcguire** [comment]
@boldor @BakingSoda :

re page margins ... your specific usecase is: "increasing fonts to improve accessibility." but the abstracted usecase is: "user wishes to increase or decrease font-size/line-height" ...in addition to existing ability to change page size.

This is why page margins might be important : since currently PB is set up to enable user to decide page size ranging from (big) 8.5x11in to (small) 4.5x7in.  but page margins are mostly designed assuming 6x9in (or 5.5x8.5in). 

so for a 8.5x11 textbook you may want: 
-- bigger fonts (with corresponding lineheight)
-- for legibility/design balance, you would also want larger margins.

And, since we are building one set of options -- we might as well consider adding the others?

**Comment by bdolor** [comment]
The way you describe it makes sense. While I can't point to any one authority on accessibility guidelines for margins in print material, I see that it can be a consideration. A lot of them use language like 'generous' margins. Only one specifies a specific measurement. 

http://www.swarthmore.edu/physical-access-and-learning-support/accessibility-guidelines-print-materials
http://www.visability.com.au/community-education/providing-access/print-materials/#guide
http://www.maraclepress.com/2012/03/clear-print-accessiblity-guidelines/

For clarity, are you describing a manual approach where the user can select the margin size they want, or are you describing a semi-automated sizing feature, where a default margin size is tied to a page-size selection?

**Comment by hughmcguire** [comment]
Hi Brad,

Your driver is accessibility, mine is more flexibility for outputs (which includes Accessibility as a subset driver). So I guess we could just let user add what they like. I would think something like: 

Page margins: 
Theme default 
OR: 
LEFT Page: 
top: ____________in 
right: ____________in 
bottom: ____________in 
left: ____________in  

LEFT Page: 
top: ____________in 
right: ____________in 
bottom: ____________in 
left: ____________in

**Comment by hughmcguire** [comment]
and then the css is: 

@page:left {
margin-top: Xin;
margin-right: Yin;
margin-bottom: Zin;
margin-left: Ain;}

@page:right {
margin-top: Bin;
margin-right: Cin;
margin-bottom: Din;
margin-left: Ein;}

(or CM).

**Comment by bdolor** [comment]
That totally works for me. Manual entry will be much easier.

**Comment by hughmcguire** [comment]
@bdolor stop me if you've heard the song "radical feature creep" before ... but: 

1. there is ONE more frequently-asked for "layout structural" modification we are often asked for, which is: 
* All chapters open on right-hand page
vs.
* chapters  can open on left or right-hand page

(I can supply the CSS).

2. And thinking of extending this & really giving user the control ... to make customization easier ... 
Currently our solution for users customizing something in the CSS is to:
a. In Appearance --> select Custom CSS Theme
b. Select a base theme
c. Customize the whole shebang of CSS (which can be overwhelming).

What if instead (or in addition) we offered on the Theme Options Page...
Enter custom CSS:
[big textbox]

Which would allow someone to inject, at the bottom of the existing CSS ... for instance: 

div.exercise-questions {
color: red;
background-color: yellow;
border: 1px solid blue;
}

Or whatever the hell they want? This would make it miles easier to add small CSS tweaks extensions without all the rigamarole.

**Comment by greatislander** [comment]
@hughmcguire re: your last comment—please create a new issue as this is outside the scope of @bdolor and @BakingSoda's pull request.

**Comment by hughmcguire** [comment]
@bdolor as per @greatislander's scolding message, please ignore everything after: 
"stop me if you've heard the song "radical feature creep" before ... but:"

**Comment by bdolor** [comment]
Someone's gotta keep you in line...FWIW, I do occasionally hear that song being played around here at the office. It's mostly nostalgia for me though, circa 2005. It stopped getting a lot of airplay after MS Office introduced the 'ribbon' — aka the *only* answer to scope creep. So, my answer to your feature request is 'ribbon'.

**Comment by hughmcguire** [comment]
@bdolor ... i'm about 95% finished emifying Luther for this project ... but I've managed to get my whole Pressbooks local install all borked up. So. behind schedule.

**Comment by hughmcguire** [comment]
@bdolor @BakingSoda I've just pushed some changes to Luther (on dev) that emify the fonts... so changing body font size should change the whole shebang. Over to you.

**Comment by bdolor** [comment]
excellent - we'll pull in your changes today, adjust, and push back to this PR.

**Comment by hughmcguire** [comment]
@bdolor OK once tested & okay'd then I will revise the other open source themes to support the emified fonts as well.

**Comment by bdolor** [comment]
I'll clean up this commit history a bit...

**Comment by bdolor** [comment]
@greatislander @hughmcguire this is now ready for review.

**Comment by bdolor** [comment]
@greatislander If you have time, would you be able to have a look at this today? Thanks — I know you're busy.

**Comment by greatislander** [comment]
Hi @bdolor! Will do—sorry, this went under my radar somehow.

**Comment by greatislander** [comment]
A couple things:

- accessibility misspelled on the options page
- when I enable and then disable the web book font size selector, there's an html element left behind that creates a white space above the top toolbar: `<div class="a11y-toolbar"><ul></ul></div>`
- when wp_debug is enabled I get an undefined index error when visiting web books before the font size selector has been enabled, e.g∴ `Notice: Undefined index: accessibility_fontsize in /Users/ned/Sites/pressbooks.com/wp-content/plugins/pressbooks/themes-book/pressbooks-book/content-accessibility-toolbar.php on line 8`

Can you make these tweaks and then ping me? Thanks @bdolor!

**Comment by bdolor** [comment]
Thank you @greatislander — @BakingSoda can you take a look?

**Comment by greatislander** [comment]
(PDF export looks great, by the way! I think it's just webbook issues at this point.)

**Comment by greatislander** [comment]
Thanks!

**Pull request merged**
