### PR TITLE
fix: repair broken urls after EPUB file import

### PR DESCRIPTION
**Pull request by dominik**
@see https://pressbooks.community/t/after-import-of-epub-file-internal-hyperlinks-are-broken/2384

### CODE REVIEW

**Comment by SteelWagstaff** [comment]
Hi @dominik thank you for submitting a PR to Pressbooks -- I will assign this to a reviewer on our dev team shortly. 

Before I do, I can see two two automatic checks that are failing but should have quick fixes if you're willing to submit them. 

1. We have an action that enforces PR branch name and commit conventions that could easily be fixed if you'd be willing/able to rename your PR branch to `fix/repair-urls-epub-import` or something like that. The important part is the `fix/` piece. 
2. We also have some automatic linting rules that are failing that could be resolved by running `composer fix` locally (this command is an alias for `vendor/bin/phpcbf --standard=phpcs.ruleset.xml *.php inc/ bin/`). 
 
Sorry we didn't have great documentation in place around expectations when you first opened this.

**Review by SteelWagstaff — CHANGES_REQUESTED** [review]
Two requested changes that came up from our automatic pipeline that need resolution: 
1. Please rename your PR branch to `fix/repair-urls-epub-import` or something like that. The important part is that the branch begin with `fix/`.
2. Please run `composer fix` or `vendor/bin/phpcbf --standard=phpcs.ruleset.xml *.php inc/ bin/` to resolve the `Generic.WhiteSpace.DisallowSpaceIndent.SpacesUsed` linting nags visible here: https://github.com/pressbooks/pressbooks/actions/runs/4977306600/jobs/8948391077?pr=3314

**Comment by dominik** [comment]
Hi @SteelWagstaff

Renaming is no problem but I ran into problems while executing the code
fixer:
$ composer fix
> vendor/bin/phpcbf --standard=phpcs.ruleset.xml *.php inc/ bin/
ERROR: The file "*.php" does not exist.

And

$ vendor/bin/phpcbf --standard=phpcs.ruleset.xml
inc/modules/import/epub/class-epub201.php
PHP Fatal error:  Uncaught PHP_CodeSniffer\Exceptions\RuntimeException:
trim(): Passing null to parameter #1 ($string) of type string is deprecated
in
pressbooks.git\vendor\wp-coding-standards\wpcs\WordPress\Sniffs\WP\I18nSniff.php
on line 194 in
pressbooks.git\vendor\squizlabs\php_codesniffer\src\Runner.php:608

I'm using PHP 8.2.1 and PHP_CodeSniffer version 3.7.2 ...

Any recommendations?

Many thanks and kind regards
Dominik

Am Di., 16. Mai 2023 um 21:36 Uhr schrieb Steel Wagstaff <
***@***.***>:

**Comment by dominik** [comment]
Never mind ... it works fine on Linux - update will follow shortly

Am Mi., 17. Mai 2023 um 10:10 Uhr schrieb Dominik Blunk ***@***.***>:

**Comment by dominik** [comment]
See new PR https://github.com/pressbooks/pressbooks/pull/3321

**Pull request closed without merging**
