### PR TITLE
create new filter hook 'pb_cover_image'

### PR DESCRIPTION
**Pull request by monkecheese**
This will allow users who are not storing images locally on the
server to hook in to this filter and use either the data in the
$cover variable or the data in $metadata['pb_cover_image'], in
order to get cover images to display correctly depending on 
their specific use case.

### CODE REVIEW

**Comment by greatislander** [comment]
Hi @monkecheese, this is a much preferable solution to me. Can I get you to document the hook in the line preceding its first use? I was doing some research into inline documentation and I am going to try to do this for all existing filter and action hooks. https://make.wordpress.org/core/handbook/best-practices/inline-documentation-standards/php/#4-hooks-actions-and-filters

**Comment by monkecheese** [comment]
sure thing, @greatislander!

**Comment by monkecheese** [comment]
@greatislander, what version of pressbooks would this be rolled out in?  (i need to put something for the "@since" in the inline documentation)

**Comment by greatislander** [comment]
@monkecheese 3.9.5.1. Thanks!

**Pull request merged**
