### PR TITLE
Upgrade Docraptor / PrinceXML

### PR DESCRIPTION
**Pull request by fdalcin**
Issue #2228 

This PR upgrades [docraptor/docraptor](https://github.com/DocRaptor/docraptor-php) to v2 and changes the pipeline to use the latest version of PrinceXML.

For now, [guzzlehttp/guzzle](https://github.com/guzzle/guzzle) needs to be locked on version ^6.2 because docraptor has no support for ^7.0. See https://github.com/DocRaptor/docraptor-php/issues/23 and https://github.com/DocRaptor/docraptor-php/pull/24

#### How to test

1. Generate a book export and a book cover export using the dev branch.
1. Switch to this branch and `composer install` to update dependencies.
1. Generate new book and cover exports.
1. Both export versions should be equal.

### CODE REVIEW

**Comment by richard015ar** [comment]
We had a review meeting and we realized that we need to upgrade Guzzle in order to make this change work.
To enable DocRaptor locally, in the `site/.env` file we need to add: `DOCRAPTOR_API_KEY='YOUR_API_KEY_HERE'`.
Once it is added, the export routine will use DocRaptor instead just Prince to export in PDF format.

This is the error displayed in the logs:
```
[error] 917#917: *81 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 10.0.2.2:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.50.1, server: pressbooks.test, request: "GET /taxonomy3/wp-admin/admin-ajax.php?action=export-book&_wpnonce=0f631ebbdf&export_formats%5Bdocraptor_print%5D=1 HTTP/2.0", upstream: "fastcgi://unix:/var/run/php-fpm-wordpress.sock:", host: "pressbooks.test", referrer: "https://pressbooks.test/taxonomy3/wp-admin/options.php?page=pb_export"
2021/08/09 15:43:34 [error] 917#917: *81 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined method GuzzleHttp\Utils::chooseHandler() in /srv/www/pressbooks.test/current/vendor/guzzlehttp/guzzle/src/functions.php:61
Stack trace:
#0 /srv/www/pressbooks.test/current/web/app/plugins/pressbooks/vendor/guzzlehttp/guzzle/src/HandlerStack.php(42): GuzzleHttp\choose_handler()
#1 /srv/www/pressbooks.test/current/web/app/plugins/pressbooks/vendor/guzzlehttp/guzzle/src/Client.php(65): GuzzleHttp\HandlerStack::create()
#2 /srv/www/pressbooks.test/current/web/app/plugins/pressbooks/vendor/docraptor/docraptor/lib/DocApi.php(77): GuzzleHttp\Client->__construct()
#3 /srv/www/pressbooks.test/current/web/app/plugins/pressbooks/inc/modules/export/prince/class-docraptor.php(62): DocRaptor\DocApi->__construct()
#4 /srv/www/pressbooks.test/current/web/app/plugins/pressbooks/inc/modules/export/class-export.php(792): Pressbooks\Modules\Export\Prince\Docraptor->convert()
#5 /srv/www/pressbooks.test/current/web/app/plugins/pressbooks/inc/class-events...PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 10.0.2.2:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading upstream, client: 192.168.50.1, server: pressbooks.test, request: "GET /taxonomy3/wp-admin/admin-ajax.php?action=export-book&_wpnonce=0f631ebbdf&export_formats%5Bdocraptor_print%5D=1 HTTP/2.0", upstream: "fastcgi://unix:/var/run/php-fpm-wordpress.sock:", host: "pressbooks.test", referrer: "https://pressbooks.test/taxonomy3/wp-admin/options.php?page=pb_export"
```

@fdalcin found a [PR for the DocRaptor lib that adds Guzzle v7 compatibility](https://github.com/DocRaptor/docraptor-php/pull/24) and seems to solve the problem. He will test and discuss with the team the alternatives.

**Comment by SteelWagstaff** [comment]
Blocked by https://github.com/DocRaptor/docraptor-php/issues/23 + https://github.com/DocRaptor/docraptor-php/pull/24. Once those are fixed upstream, we can revisit this PR

**Review by SteelWagstaff — COMMENTED** [review]
@fdalcin i was able to upgrade to DocRaptor 2.0 and downgrade to Guzzle 6.5.5 by running `composer update docraptor/docraptor --with-all-dependencies`. I commited the changes to composer.json and composer.lock. If this still allows us to produce PDF exports, maybe this allows us to proceed even before upstream changes are merged?

**Comment by fdalcin** [comment]
closing this in favor of #2538

**Pull request closed without merging**
