### PR TITLE
stop the madness, unnecessary array reversal

### PR DESCRIPTION
**Pull request by bdolor**
Problem: All multiple metadata fields passed to Custom Metadata Manager get reversed on every save. Affects contributing author, keywords, bisac subject in 'Book Info'. Should contributing authors be listed on the cover page, as contributing author 1, contributing author 2, contributing author 3, contributing author 4, each subsequent save of 'Book Info' will reverse this order. 

As the [Custom Metadata Manager](https://wordpress.org/plugins/custom-metadata/) hasn't been updated in a while, it feels low risk to affect the plugin code directly. Besides that, I can't see the purpose of `array_reverse()` in this particular circumstance — please shed some light on it if you know. 

...save:
screen shot 2015-03-06 at 3 17 02 pm

...and save again: 
screen shot 2015-03-06 at 3 16 13 pm

### CODE REVIEW

**Comment by greatislander** [comment]
Hi @bdolor, it looks like they may have fixed this in http://github.com/Automattic/custom-metadata. If so I'd rather just update the version we include to their current one. Do have time to look into this? Otherwise I'm happy to do so.

**Comment by bdolor** [comment]
I've forced an update of this branch to instead use the latest version of custom metadata.

**Comment by greatislander** [comment]
Fantastic, thanks!

**Comment by connerbw** [comment]
Hi,

The plugin included in PressBooks was forked by me.  My patches were never merged back in, even though I made a pull request

"Garbage prevention" [1] is hopefully fixed, but I know that the checkboxes aren't. [2] You might want to check the look and feel of anything that used them.

[1] https://github.com/connerbw/custom-metadata/commit/c9c5c52cb964e6d3a7f817e3a89fac21036050e0

[2]https://github.com/connerbw/custom-metadata/commit/845fee144a0d607f9eccaa04cad057979b9a91ab

screenshot - 15-03-12 - 10 52 37 pm

**Pull request merged**
