### PR TITLE
Fix contributor exports

### PR DESCRIPTION
**Pull request by SteelWagstaff**
Partial fix for #2371

### CODE REVIEW

**Review by fdalcin — CHANGES_REQUESTED** [review]
Everything LGTM @arzola. 

As we discussed just now, this PR just needs to port template changes related to screen-reader texts from https://github.com/pressbooks/pressbooks-book/pull/857.

**Comment by fdalcin** [comment]
@SteelWagstaff @arzola Web book looks good and the styling is nice while changing themes as well.

While testing exporting PDFs and EPUBs I noticed some styling issues
1. Name seems to not be aligned properly
2. Screen reader text is being rendered when it shouldn't -- website:
3. Links seem to be breaking lines -- not sure if is the intended behaviour
image

4. The contributors back-matter post type seems to not replace links properly
image

**Comment by arzola** [comment]
@fdalcin I sent the fix for the point 4

**Comment by fdalcin** [comment]
@arzola added a friendly commit to remove `role="presentation"` that was causing EPUB validation erros.

**Comment by arzola** [comment]
@fdalcin I also sent a little commit to fix an unclosing section div for exports

**Review by fdalcin — APPROVED** [review]
@arzola LGTM now. Tested again viewing the book page and exporting the book. 

Screen reader texts don't appear anymore on exports, no validation errors, and styling is better after removing screen reader texts. Links are breaking to a new line because they are too long, so I think it's fine.
image

**Pull request merged**
