### PR TITLE
Replace print pdf icon

### PR DESCRIPTION
**Pull request by SteelWagstaff**
This PR fixes https://github.com/pressbooks/pressbooks/issues/2264 and https://github.com/pressbooks/pressbooks/issues/2266

To test:
1. Produce a Print PDF export
2. Check to see that the new icon appears on the export page. The icon should have a red banner and should include the text 'Print PDF'

**Note:** I did not replace the 36 and 72 px versions of this image as they are not used anywhere in Pressbooks. The large size is explicitly specified for the export table, which is the only place these icons are currently used in Pressbooks: https://github.com/pressbooks/pressbooks/blob/86b921b5c3ede76e3fd94732e56cce50c710ded8/inc/modules/export/class-table.php#L414-L416

### CODE REVIEW

**Comment by SteelWagstaff** [comment]
@greatislander Is there a historical reason why we need to leave the small sizes of export icons SCSS https://github.com/pressbooks/pressbooks/blob/86b921b5c3ede76e3fd94732e56cce50c710ded8/assets/src/styles/export.scss#L96-L198 and the corresponding image assets in Pressbooks?

**Review by fdalcin — DISMISSED** [review]
LGTM @SteelWagstaff 

Screen Shot 2021-07-21 at 10 04 56

**Comment by greatislander** [comment]
> @greatislander Is there a historical reason why we need to leave the small sizes of export icons SCSS and the corresponding image assets in Pressbooks?

@SteelWagstaff Nope. It used to be that the exports were displayed in a grid, with the most recent of each format as large icons and then a more compact grid with smaller icons below. These can and should be removed.

**Comment by SteelWagstaff** [comment]
@fdalcin Just pushed a commit which removes the unused small sizes of file export icons. If it still looks good to you, please squash and merge at your convenience.

**Pull request merged**
