### PR TITLE
corrected typo in list of dependencies

### PR DESCRIPTION
**Pull request by sillybean**

### CODE REVIEW

**Comment by greatislander** [comment]
Thanks @sillybean!

**Comment by hughmcguire** [comment]
ooh look at that a commit from the the outerworld ! hi @sillybean long time no talk ...

**Comment by hughmcguire** [comment]
or rather a pull request ...

**Comment by sillybean** [comment]
Hi, @hughmcguire! I finally got around to installing this locally to see about adding syntax highlighting. (This is some epic procrastination on my part... but I really would rather support Pressbooks than fiddle with my own file formatting.)

**Pull request merged**
