### PR TITLE
fix: add build tools as devDependency, fix linting errors (fix #2235)

### LINKED ISSUE #2215: Fix division-related deprecation warnings for Dart Sass 2.0.0
When running npm run build:production, I get the following alerts in the console, related to our use of division:

```
DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div(2, 18)

More info and automated migrator: https://sass-lang.com/d/slash-div

   ╷
36 │     letter-spacing: (2 / 18) * 1em;
   │                      ^^^^^^
   ╵
    stdin 36:22  root stylesheet

DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div(1, 6)

More info and automated migrator: https://sass-lang.com/d/slash-div

   ╷
87 │       padding-bottom: (1 / 6) * 100%;
   │                        ^^^^^
   ╵
    stdin 87:24  root stylesheet

DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($wp-spinner-size-inner, 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

    ╷
288 │       margin-left: -($wp-spinner-size-inner / 2);
    │                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ╵
    stdin 288:22  root stylesheet

DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div(15, 13)

More info and automated migrator: https://sass-lang.com/d/slash-div

   ╷
10 │     font-size: #{(15 / 13)}em;
   │                   ^^^^^^^
   ╵
    stdin 10:19  root stylesheet

DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div(15, 13)

More info and automated migrator: https://sass-lang.com/d/slash-div

   ╷
10 │     font-size: #{(15 / 13)}em;
   │                   ^^^^^^^
   ╵
    stdin 10:19  root stylesheet

DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div(2, 18)

More info and automated migrator: https://sass-lang.com/d/slash-div

   ╷
36 │     letter-spacing: (2 / 18) * 1em;
   │                      ^^^^^^
   ╵
    stdin 36:22  root stylesheet

DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div(1, 6)

More info and automated migrator: https://sass-lang.com/d/slash-div

   ╷
87 │       padding-bottom: (1 / 6) * 100%;
   │                        ^^^^^
   ╵
    stdin 87:24  root stylesheet

DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($wp-spinner-size-inner, 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

    ╷
288 │       margin-left: -($wp-spinner-size-inner / 2);
    │                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ╵
    stdin 288:22  root stylesheet
```

### LINKED ISSUE #2235: Add pressbooks-build-tools as dev-dependency
Dac set up no-install-build tools because dependabot alerts were so annoying. Ned suggests that it would be better to install build tools locally, but remove nags by better configuring the dependabot rules so that we only get alerts in repos for what we want. We should set up dependabot alerts in pressbooks-build-tools only and really only need to bump them when there are other changes we want to make to that repo, since we're not vulnerable to any security problems from this. This would also involve adding pressbooks-build-tools as a dev-dependency for any of the repos which use it.

Task:
- [x] Require pressbooks-build-tools as dev dependency for Pressbooks (and other repos which use build tools)
- [x] Update documentation to remove -no-save install steps
- [x] #2236

### PR DESCRIPTION
**Pull request by greatislander**
This PR does a few things:

1. Adds Pressbooks Build Tools as a devDependency (fixes #2235).
2. Renames default GitHub Actions workflow from "PHPUnit" to the more accurate "Lint and test" and adds JS and Sass linting to the steps.
3. Fixes JS linting errors resulting from updated linter configuration.
4. Resolves deprecation issues with [Sass division](https://sass-lang.com/documentation/breaking-changes/slash-div) (fixes #2215) 

In addition, it removes an unnecessary script, `cssanimations.js`, which was used to test browsers for CSS Animations support. This has been replaced with a CSS `@supports` query in 78eb3c90.

### CODE REVIEW

**Review by SteelWagstaff — APPROVED** [review]
LGTM

**Review by SteelWagstaff — CHANGES_REQUESTED** [review]
@greatislander Ned the changes you make generally look good to me, but I did notice that this PR replaces the new cover image we just released with the old 'red typewriter' ones. Can you merge the latest version of dev branch to your PR branch so that your branch includes the new cover image files? Here's the commit we need: https://github.com/pressbooks/pressbooks/pull/2226

**Comment by greatislander** [comment]
> @greatislander Ned the changes you make generally look good to me, but I did notice that this PR replaces the new cover image we just released with the old 'red typewriter' ones. Can you merge the latest version of dev branch to your PR branch so that your branch includes the new cover image files? Here's the commit we need: #2226

@SteelWagstaff: the issue here is that in your PR, you replaced the compiled assets (in `/assets/dist/images`) rather than the source (in `/assets/src/images`). I will make the change, but for future reference, the files in `/assets/dist` shouldn't be modified— they are rebuilt every time someone runs `npm run production` and I just happened to be the first person to do that since #2226.

**Comment by SteelWagstaff** [comment]
Whoops! Sorry about that.

**Comment by SteelWagstaff** [comment]
@greatislander We merged the image fix to dev this morning. If you pull latest changes and rerun `npm run build`, I think this PR should be mergeable.

**Review by SteelWagstaff — APPROVED** [review]
LGTM. Will merge once checks complete.

**Pull request merged**
