### PR TITLE
Update wp-admin-colors to 5.3.1

### PR DESCRIPTION
**Pull request by connerbw**
Changes made upstream.

https://github.com/WordPress/WordPress/commits/5.3-branch/wp-admin/css/colors/_admin.scss

Annotation 2019-12-16 104417

Left side: 5.3.1
Right side: 5.3

Annotation 2019-12-16 104120
Annotation 2019-12-16 104225

### CODE REVIEW

**Comment by mcgratay** [comment]
Places where the buttons are white/red instead of white/black: 

- Post creation buttons on Organize page 
Screen Shot 2019-12-16 at 11 53 21 AM

- Any "Add New" button anywhere
Screen Shot 2019-12-16 at 11 50 19 AM

- My Catalog page
Screen Shot 2019-12-16 at 11 53 09 AM

- Rootsite > Appearance > Menus 
Screen Shot 2019-12-16 at 11 52 35 AM

**Comment by connerbw** [comment]
CSS class: **page-title-action**. Color: red

We set 

```scss
$monza: #d4002d;
$link: darken($monza, 5%);
$link-focus: $monza;
```

 + https://github.com/pressbooks/pressbooks/blob/5e74a04042b5c0db36345642f616fa126c41d44b/assets/src/styles/colors-pb.scss#L164-L184


CSS class: **button**. Color: gray

We set 

```scss
$monza: #d4002d;
$button-color: $monza;
``` 

but this no longer works because `$button-color` is now hardcoded to `#7e8993` and `#32373c` in WordPress core.

+ https://github.com/pressbooks/wp-admin-colors/blob/08a234cc5a11c2c3d638352d02ea006e572dac6a/dist/_admin.scss#L76-L88
+ https://github.com/WordPress/WordPress/blob/8894c0f1a25df9581537a06fc6f03614ecb39f90/wp-admin/css/colors/_admin.scss#L76-L88
+ https://github.com/WordPress/WordPress/commit/20e18613d0a3f70ebe4766f50f39aaf5cd9dec0a

**Comment by connerbw** [comment]
https://github.com/WordPress/WordPress/commit/20e18613d0a3f70ebe4766f50f39aaf5cd9dec0a#r36452556

**Comment by SteelWagstaff** [comment]
Received a reply from upstream -- these changes were intentional. Here is the related devnote: https://make.wordpress.org/core/2019/12/10/alternate-color-schemes-changes-in-wordpress-5-3-1/  

> Secondary button styles will be the same for all bundled alternate color schemes. This change also fixes the :active state CSS issue. Please note this change also introduces some hardcoded colors for both gray borders and texts. Plugin authors who provide specific support for alternate color schemes can use these new hardcoded colors.

and here is the specific ticket: https://core.trac.wordpress.org/ticket/48585#comment:29. Last comment in ticket says

> these secondary buttons are not meant to be customizable, hence not using variables.

**Pull request merged**
