### PR TITLE
Don't process images if they are embedded base64 strings

### PR DESCRIPTION
**Pull request by BenGig**
refers to issue #2106

### CODE REVIEW

**Comment by BenGig** [comment]
I fixed the code style issues in my changes. Sadly I cannot see where the style issues in the other file (not touched by me) come from.

**Comment by SteelWagstaff** [comment]
Thanks @BenGig -- we're seeing the same test failures in another PR and think it may be a Travis CI issue unrelated to any changes you're proposing. Hopefully we'll get that squared away soon and will be able to review this properly before long.

**Comment by SteelWagstaff** [comment]
@BenGig We've rerun the build -- all tests pass now, but we now have a CodeCov nag because no unit test was submitted with the code change. Do you have any experience using [PHPUnit](https://phpunit.de/) to write unit tests for PHP functions? If so, would you be willing to write a small test for the change you're proposing? See https://docs.pressbooks.org/unit-testing/. If not, our team should be able to assist at some point soon.

**Comment by BenGig** [comment]
I have no experience with PHPUnit, but with (unit) testing as such, with other frameworks like pytest and molecule. Can you point me to the test unit which already does tests on this part of the code?

**Comment by SteelWagstaff** [comment]
@BenGig All tests for the repo live in https://github.com/pressbooks/pressbooks/tree/dev/tests. You'd probably want to put unit tests for this new behavior in https://github.com/pressbooks/pressbooks/blob/dev/tests/test-modules-import.php? Upon my own cursory initial review of what you're proposing, I suspect that we'll have some concerns about accepting unvalidated base64 code into a Pressbooks import without stronger sanitization/validation than the simple `str_contains` check proposed here. See https://stackoverflow.com/questions/12658661/validating-base64-encoded-images. All this to say that it'll take a bit longer for us to review what probably appears to you to be a simple PR, as our devs and security team will need to take a closer look. You're welcome to use your proposed approach in your own local fork in the meantime?

**Comment by SteelWagstaff** [comment]
@BenGig turns out I didn't properly understand what your PR was doing and gave some misleading answers previously. I don't think you need to do anything else at present re: security improvements or unit tests. I'll ask the dev team to take a closer look and see if we can get your PR reviewed properly soon. Sorry for all the back and forth on this.

**Review by arzola — CHANGES_REQUESTED** [review]
@SteelWagstaff @richard015ar @fdalcin  

I tested it locally and works properly but creating a "unit" or feature test for this could be time consuming, we need to create a wordpress xml template that contains some base64 images embeded and then create the test using that file.

My thoughts

1. I think it's not a common thing to have images embeded like that and users usually don't import wordpress content using this method but still there are a few users that could be benefit of this

I suggest to ignore coverage for this block, and create a ticket to test the **class-downloads.php** file because this file is not being tested at all (just if this feature is highly used)

```
// @codeCoverageIgnoreStart
if ( str_contains( $src_old, ';base64,' ) ) {
continue;
}
// @codeCoverageIgnoreEnd
```

2. We could also discard this change if we think we won't want to support this change

**Comment by SteelWagstaff** [comment]
@BenGig Closing this PR in favor of https://github.com/pressbooks/pressbooks/pull/2132, which has been merged to dev. Our next release of Pressbooks (early-mid next week) should include these changes.

**Pull request closed without merging**
